In [ ]:
import numpy as np

a=np.array([1,2,3])
b=np.array([1,2,3])
print(a*b)

[1 4 9]


numpy :
1.Faster than list
2.less storage memory
3.no type checking while iterating
4.contiguous memory
SIMD-single instruction multiple data
SIMD VECTOR PROCESSING(memory next to each other)eg:addition
effective cache utilization
5.Application:
matlab replacemant
matplotlib
backend(pandas,connect 4 , photography)
ml

In [ ]:
#basics
import numpy as np

a=np.array([[1,2,3],[9,8,7]],dtype='int16')
print(a.ndim)#no of dimension
print(a.shape)#shape(list,elements)
print(a.dtype)#data type
print(a.itemsize)#no of bytes
print(a.size)#total size-no of elements
print(a.size*a.itemsize)#total print(a.nbytes)

print(np.zeros(2))

2
(2, 3)
int16
2
6
12
[0. 0.]


In [ ]:
import numpy as np

a=np.array([[1,2,3,4,5],[5,6,7,8,9],[1,9,2,8,3]])
print(a)
print(a[0,2])
print(a[2,4])
print(a[1,:])#row
print(a[:,1])#colunm
print(a[2,0::2])#start-stop-step

[[1 2 3 4 5]
 [5 6 7 8 9]
 [1 9 2 8 3]]
3
3
[5 6 7 8 9]
[2 6 9]
[1 2 3]


zeros()
ones()
full()
full_like()
np.random.ram()

In [ ]:
import numpy as np

a=np.array([[1,2,3,4,5],[5,6,7,8,9],[1,9,2,8,3]])
print(a)
b=np.zeros((2,3))
print(b)
c=np.ones((3,5))
print(c)
d=np.full((3,5),13)
print(d)
e=np.full_like(a,6)
print(e)
f=np.random.rand(3,4)
print(f)
g=np.random.randint(7,size=(2,2))
print(g)

[[1 2 3 4 5]
 [5 6 7 8 9]
 [1 9 2 8 3]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[13 13 13 13 13]
 [13 13 13 13 13]
 [13 13 13 13 13]]
[[6 6 6 6 6]
 [6 6 6 6 6]
 [6 6 6 6 6]]
[[0.69791353 0.90835605 0.03633203 0.37162749]
 [0.75684479 0.1473078  0.74162438 0.89134578]
 [0.59664713 0.62299588 0.40879177 0.29201312]]
[[4 3]
 [4 5]]
