In [63]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import accuracy_score

In [30]:
df=pd.read_excel("/content/diabetes.xls")

In [31]:
df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [32]:
df.columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')

In [33]:
x=df[['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age']]

In [34]:
y=df[['Outcome']]

In [35]:
x


Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  
0                       0.627   50  
1                       0.351   31  
2                       0.672   32  
3                       0.167   21  
4                       2.288   33  
..                        ...  ...  
763                     0.171   63  
764                     0.340   27  
765                     0.245   30  
766                     0.349   47  
767                     0.315   23  

[768 rows x 8 columns]

In [36]:
y

Outcome
0          1
1          0
2          1
3          0
4          1
..       ...
763        0
764        0
765        0
766        1
767        0

[768 rows x 1 columns]

In [43]:
x_train, x_test  , y_train ,y_test=train_test_split(x,y , test_size=0.2)

In [64]:
model1=DecisionTreeClassifier()
model2=RandomForestClassifier()
model3=KNeighborsClassifier()
model4=GradientBoostingClassifier()

In [65]:
model1.fit(x_train,y_train)

DecisionTreeClassifier()

In [66]:
model2.fit(x_train,y_train)

<ipython-input-66-6a5ebefbb85f>:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  model2.fit(x_train,y_train)


RandomForestClassifier()

In [67]:
model3.fit(x_train,y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier()

In [70]:
model4=model4.fit(x_train,y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/ensemble/_gb.py:437: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [71]:
model1=model1.predict(x_test)

In [72]:
model2=model2.predict(x_test)

In [73]:
model3=model3.predict(x_test)

In [74]:
model4=model4.predict(x_test)

In [75]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [76]:
accuracy = accuracy_score(y_test, model1)
print(f'Accuracy: {accuracy}')
print('Classification Report:')
print(classification_report(y_test, model1))
print('Confusion Matrix:')
print(confusion_matrix(y_test, model1))

Accuracy: 0.6948051948051948
Classification Report:
              precision    recall  f1-score   support

           0       0.75      0.78      0.77        99
           1       0.58      0.55      0.56        55

    accuracy                           0.69       154
   macro avg       0.67      0.66      0.66       154
weighted avg       0.69      0.69      0.69       154

Confusion Matrix:
[[77 22]
 [25 30]]


In [77]:
accuracy = accuracy_score(y_test, model2)
print(f'Accuracy: {accuracy}')
print('Classification Report:')
print(classification_report(y_test, model2))
print('Confusion Matrix:')
print(confusion_matrix(y_test, model2))

Accuracy: 0.7532467532467533
Classification Report:
              precision    recall  f1-score   support

           0       0.78      0.86      0.82        99
           1       0.69      0.56      0.62        55

    accuracy                           0.75       154
   macro avg       0.73      0.71      0.72       154
weighted avg       0.75      0.75      0.75       154

Confusion Matrix:
[[85 14]
 [24 31]]


In [78]:
accuracy = accuracy_score(y_test, model3)
print(f'Accuracy: {accuracy}')
print('Classification Report:')
print(classification_report(y_test, model3))
print('Confusion Matrix:')
print(confusion_matrix(y_test, model3))

Accuracy: 0.6883116883116883
Classification Report:
              precision    recall  f1-score   support

           0       0.73      0.81      0.77        99
           1       0.58      0.47      0.52        55

    accuracy                           0.69       154
   macro avg       0.66      0.64      0.64       154
weighted avg       0.68      0.69      0.68       154

Confusion Matrix:
[[80 19]
 [29 26]]


In [79]:
accuracy = accuracy_score(y_test, model4)
print(f'Accuracy: {accuracy}')
print('Classification Report:')
print(classification_report(y_test, model4))
print('Confusion Matrix:')
print(confusion_matrix(y_test, model4))

Accuracy: 0.7662337662337663
Classification Report:
              precision    recall  f1-score   support

           0       0.79      0.87      0.83        99
           1       0.71      0.58      0.64        55

    accuracy                           0.77       154
   macro avg       0.75      0.73      0.73       154
weighted avg       0.76      0.77      0.76       154

Confusion Matrix:
[[86 13]
 [23 32]]
